# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ruby-grep"
  s.version = ""

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["aleks tkach"]
  s.date = "2013-08-12"
  s.description = "enhaced grep program: higlights matches & filenames, shows line numbers"
  s.email = "ale.tkachenko@gmail.com"
  s.executables = ["ruby-grep"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "bin/ruby-grep",
    "lib/ruby-grep.rb",
    "lib/ruby-grep/directory.rb",
    "lib/ruby-grep/expression.rb",
    "lib/ruby-grep/file.rb",
    "lib/ruby-grep/line.rb",
    "ruby-grep screenshot.png",
    "ruby-grep.gemspec",
    "spec/directory_spec.rb",
    "spec/expression_spec.rb",
    "spec/file_spec.rb",
    "spec/fixtures/test_file.txt",
    "spec/line_spec.rb",
    "spec/spec_helper.rb",
    "spec/test_data.rb"
  ]
  s.homepage = "http://github.com/alekstkach/ruby-grep"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "enhaced grep program: higlights matches & filenames, shows line numbers"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<colorize>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<debugger>, [">= 0"])
    else
      s.add_dependency(%q<colorize>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<debugger>, [">= 0"])
    end
  else
    s.add_dependency(%q<colorize>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<debugger>, [">= 0"])
  end
end

